# SPDX-FileCopyrightText: 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "21:00"
      timezone: "America/Los_Angeles"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "21:00"
      timezone: "America/Los_Angeles"
