# SPDX-FileCopyrightText: 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  docker-build:
    uses: omec-project/.github/.github/workflows/docker-build-no-go.yml@main
    with:
      branch_name: ${{ github.ref }}

  hadolint:
    uses: omec-project/.github/.github/workflows/hadolint.yml@main
    with:
      branch_name: ${{ github.ref }}

  license-check:
    uses: omec-project/.github/.github/workflows/license-check.yml@main
    with:
      branch_name: ${{ github.ref }}

  fossa-scan:
    uses: omec-project/.github/.github/workflows/fossa-scan.yml@main
    with:
      branch_name: ${{ github.ref }}

